/**
 * Battle era configurations.
 * Each era defines themed text lines used during battle simulation.
 * The "mafia" era is the default and always available.
 * Exclusive eras require superadmin assignment to a guild.
 */

const BATTLE_ERAS = {
  mafia: {
    key: 'mafia',
    name: 'Mafia',
    description: 'Classic Solpranos mafia warfare — concrete shoes, cannoli, and family honor.',
    exclusive: false,
    lobbyIcon: '⚔️',
    lobbyColor: '#FFD700',
    lobbyOpening: 'The family is gathering for a showdown.',
    lobbyPlayersLabel: '🥊 Fighters',
    eliminationLines: [
      "☠️ {defender} has been iced. Room temperature.",
      "☠️ {defender} sleeps with the fishes now.",
      "☠️ {defender} got clipped. It's nothing personal, just business.",
      "☠️ {defender} won't be coming back from this one.",
      "☠️ {defender} got whacked. Say goodnight.",
      "☠️ {defender} slipped on a banana peel into a cement mixer. Classic.",
      "☠️ {defender} confused the espresso machine with a tommy gun. Fatal mistake.",
      "☠️ {defender} tried to outrun a horse. The horse won.",
      "☠️ {defender} ate the cannoli that was DEFINITELY poisoned.",
      "☠️ {defender} took a nap in the wrong trunk. Permanent nap.",
      "☠️ {defender} challenged the boss to poker. Lost everything. Including their life.",
      "☠️ {defender} got locked in the walk-in freezer. Very chilly farewell.",
      "☠️ {defender} mistook dynamite for a cigar. Explosive exit.",
      "☠️ {defender} tried to skip out on a tab at Luigi's. Luigi doesn't forget.",
      "☠️ {defender} insulted someone's mother. The streets are ruthless.",
      "☠️ {defender} walked into the wrong social club. Very wrong.",
      "☠️ {defender} bet against the family. Bad investment.",
      "☠️ {defender} forgot to pay respects. The family remembered.",
      "☠️ {defender} accidentally sat in the boss's chair. Last mistake ever.",
      "☠️ {defender} tried to rob the Solpranos piggy bank. Piggy fought back.",
      "☠️ {defender} talked to the feds. The family talked back.",
      "☠️ {defender} laughed at the wrong joke. The punchline was lethal.",
      "☠️ {defender} thought they could swim faster than the concrete. They couldn't.",
      "☠️ {defender} ordered pineapple on pizza at the family dinner. Unforgivable.",
      "☠️ {defender} tried to count cards at Tony's poker night. Tony counted them out.",
      "☠️ {defender} showed up late to a hit. Irony got them first.",
      "☠️ {defender} opened an umbrella indoors. Superstition killed them.",
      "☠️ {defender} spilled wine on the tablecloth. The family spilled their blood.",
      "☠️ {defender} forgot the boss's birthday. The boss didn't forget them.",
      "☠️ {defender} tried to parallel park the getaway car. Still parked there. Forever.",
    ],
    combatLines: [
      "{attacker} sends {defender} to sleep with the fishes for {damage} HP!",
      "{attacker} delivers an offer {defender} can't refuse - {damage} damage!",
      "{attacker} whacks {defender} with a tire iron for {damage} HP!",
      "{attacker} gives {defender} a concrete shoe fitting - {damage} damage!",
      "{attacker} breaks {defender}'s kneecaps for {damage} HP!",
      "{attacker} puts a hit on {defender} - {damage} damage taken!",
      "{attacker} makes {defender} kiss the ring... with their face! {damage} HP!",
      "{attacker} pistol-whips {defender} for {damage} damage!",
      "{attacker} sends {defender} a message - {damage} HP worth!",
      "{attacker} shows {defender} who's boss - {damage} damage!",
      "{attacker} throws {defender} through a window! {damage} HP shattered!",
      "{attacker} introduces {defender} to their baseball bat! {damage} damage!",
    ],
    flavorLines: [
      "🚬 {player} lights up a cigar and contemplates life.",
      "📞 {player} gets a call from the boss. 'Keep it clean.'",
      "🎰 {player} checks the numbers from last night's game.",
      "🚗 {player} hears sirens in the distance. Feds getting close.",
      "🎵 {player} hums 'That's Amore' while reloading.",
      "💼 {player} checks the briefcase. Everything's there.",
      "🍷 {player} swirls a glass of expensive wine.",
      "🕊️ {player} feeds the pigeons. Even killers have hobbies.",
      "🎭 {player} practices their alibi in the mirror.",
      "🌃 {player} admires the skyline. Beautiful city. Violent, but beautiful.",
      "🔫 {player} cleans their gun. Maintenance is important.",
      "📰 {player} reads the obituaries. Checking for friends.",
      "🎪 {player} juggles grenades. Just kidding. Or are they?",
      "🚪 {player} checks the exits. Always have an escape plan.",
      "👔 {player} adjusts their tie. Looking sharp for the funeral. Theirs? Who knows.",
      "🎬 {player} quotes The Godfather. Classic move.",
      "🍝 {player} debates opening a legitimate restaurant. Nah.",
      "💰 {player} counts money nervously. Is it all there?",
      "🚕 {player} hails a cab. Wait, that's not a cab driver...",
      "🎲 {player} rolls dice on the ground. Snake eyes. Bad omen.",
      "📱 {player} checks their burner phone. 47 missed calls from mom.",
      "🏪 {player} window-shops at the corner store. Maybe they'll rob it later.",
      "⛪ {player} says a quick prayer. Insurance policy.",
      "🎺 {player} hears jazz in the distance. Classy.",
      "🌹 {player} smells a rose. Then sneezes violently.",
      "🚬 {player} offers someone a cigarette. Declined. Rude.",
      "🎩 {player} tips their fedora at a passing stranger.",
      "🍕 {player} debates pineapple on pizza. Decides against it. Smart.",
      "🔮 {player} visits a fortune teller. 'I see violence.' No kidding.",
      "🎸 {player} air-guitars to Frank Sinatra. Embarrassing.",
    ],
  },

  vault_runners: {
    key: 'vault_runners',
    name: 'Vault Runners',
    description: 'Incompetent criminals pulling a heist. Ocean\'s Eleven meets Arrested Development.',
    exclusive: true,
    lobbyIcon: '🏦',
    lobbyColor: '#22c55e',
    lobbyOpening: 'The crew is assembling. Someone remembered the drill this time. Probably.',
    lobbyPlayersLabel: '🦹 The Crew',
    eliminationLines: [
      "💀 {defender} triggered the alarm by sneezing into the motion sensor. {attacker} shoved them into the laser grid on the way out.",
      "💀 {attacker} \"accidentally\" closed the vault door on {defender}. The time lock is set for 72 hours. Good luck in there.",
      "💀 {defender} got tangled in their own grappling hook and {attacker} just... watched. Popcorn and everything.",
      "💀 {attacker} swapped {defender}'s smoke bomb with a flashbang. {defender} is now blind AND arrested.",
      "💀 {defender} tried to crawl through the air vent. Got stuck at the first turn. {attacker} sealed it shut.",
      "💀 {attacker} told {defender} the getaway car was in Lot B. There is no Lot B. {defender} is still looking.",
      "💀 {defender}'s disguise was a name tag that said 'NOT A CRIMINAL.' Security disagreed. {attacker} waved goodbye.",
      "💀 {attacker} used {defender} as a human shield when the security guard dog showed up. The dog chose violence.",
      "💀 {defender} accidentally called 911 instead of the crew's burner. Gave their full name and location. {attacker} is already in the car.",
      "💀 {attacker} convinced {defender} the vault combination was their birthday. It wasn't. The alarm was loud.",
      "💀 {defender} left fingerprints on EVERYTHING including the 'Please Do Not Touch' sign. {attacker} tipped off forensics for fun.",
      "💀 {defender}'s flashlight batteries died at the worst possible moment. {attacker}'s didn't. Nature selected.",
      "💀 {attacker} told {defender} to \"hold this\" and handed them a dye pack. Three... two... one... purple.",
      "💀 {defender} wore squeaky shoes to a stealth heist. {attacker} heard them from three floors away. So did everyone else.",
      "💀 {attacker} reprogrammed the signal jammer to only jam {defender}'s radio. {defender} has been talking to nobody for twenty minutes.",
      "💀 {defender} grabbed what they thought was the diamond. It was a paperweight from the gift shop. {attacker} has the real one.",
      "💀 {defender} tried to hack the security system by typing 'password123'. It worked. Then {attacker} changed it.",
    ],
    arrestLines: [
      "🚔 {defender} got tackled by a security guard who was honestly just having a really bad day. {attacker} filmed it.",
      "🚔 {attacker} anonymously reported {defender}'s location to the cops. From ten feet away. While waving.",
      "🚔 {defender} tried to bribe the guard with Monopoly money. The guard was not amused. {attacker} provided the handcuffs.",
      "🚔 {defender} ran straight into a glass door trying to escape. Left a face print. {attacker} signed it as modern art.",
      "🚔 {defender} hid in a storage closet. It was the security office. {attacker} locked it from outside.",
      "🚔 The K-9 unit found {defender} because they had bacon in their pocket. WHY did they have bacon? {attacker} knows why.",
      "🚔 {defender} tried to blend in with the mannequins. Blinked. {attacker} yelled 'THAT ONE MOVED!' Very helpful.",
      "🚔 {defender} was caught because their getaway vehicle was a shopping cart. {attacker} popped the wheels earlier.",
      "🚔 {defender} surrendered after the security guard's walkie-talkie static scared them. {attacker} made the static noise.",
      "🚔 {defender} got arrested for trespassing, breaking and entering, AND an overdue library book. {attacker} planted the book.",
    ],
    flavorLines: [
      "🔦 {player} realizes their night-vision goggles are actually swim goggles painted black.",
      "📻 {player}'s earpiece starts picking up a local jazz station. They vibe for a second. Focus.",
      "🧤 {player} puts on their heist gloves. They're oven mitts. Close enough.",
      "🚗 {player} checks on the getaway car. It has a boot on it. That's new.",
      "🗺️ {player} unfolds the blueprint. It's upside down. Has been this whole time.",
      "💡 {player} accidentally triggers a hallway light. Freezes like a deer. Nobody noticed. Maybe.",
      "🎭 {player} adjusts their ski mask. It's on backwards. They can smell their own breath.",
      "📱 {player}'s phone goes off. The ringtone is the Mission Impossible theme. Irony is dead.",
      "🔑 {player} picks a lock in 3 seconds. Wrong door. That's a broom closet.",
      "🐕 {player} hears the security dog barking. Throws a steak. It's frozen solid. The dog is confused.",
      "💎 {player} spots the target vault. It's smaller than expected. Also it might be a safe deposit box.",
      "🧱 {player} tries to cut through a wall. Hits a water pipe. The heist is now also a pool party.",
      "🚨 {player} walks through a metal detector they didn't see. Everything beeps. Even their belt.",
      "📹 {player} waves at a security camera. Realizes. Puts hand down slowly. Damage done.",
      "🧊 {player} slips on a freshly mopped floor. The janitor watches. Judges silently.",
      "🎒 {player} opens their heist bag. It's full of sandwiches. Wrong bag. But honestly, needed those.",
      "🔧 {player} assembles the drill. Three parts are left over. That can't be good.",
      "🚪 {player} tries to open a push door by pulling. For thirty seconds. The camera got all of it.",
      "💨 {player} uses a smoke bomb for cover. In a room with smoke detectors. Sprinklers activate.",
      "🎵 {player} starts humming the heist music. The crew tells them to shut up. They hum quieter.",
      "🧲 {player} brought a magnet to disable the electronic lock. It disabled their own phone instead.",
      "📦 {player} hides behind a cardboard box. Metal Gear style. A guard kicks it. {player} says 'ow.'",
    ],
    combatLines: [
      "{attacker} throws a bag of stolen jewels at {defender}'s face! {damage} damage and a lot of scattered diamonds!",
      "{attacker} swings a gold bar at {defender}! {damage} HP of premium damage!",
      "{attacker} shoves {defender} into the laser grid! {damage} HP and a very geometric sunburn!",
      "{attacker} drops a ceiling tile on {defender} from the air vent! {damage} damage! Stealth: failed.",
      "{attacker} hits {defender} with a fire extinguisher! {damage} HP! Safety first, violence second.",
      "{attacker} throws a flash drive full of evidence at {defender}! {damage} damage! That's... not how you destroy evidence.",
      "{attacker} trips {defender} with a grappling hook! {damage} HP! Multi-purpose tool.",
      "{attacker} slams {defender} with a vault door! {damage} damage! That's gonna need some ice. And a chiropractor.",
      "{attacker} blinds {defender} with a laser pointer and kicks them down the stairs! {damage} HP!",
      "{attacker} releases the security dog on {defender}! {damage} damage! Bad dog. Good chaos.",
      "{attacker} hits {defender} with a duffle bag full of cash! {damage} HP! Most expensive punch ever.",
      "{attacker} shoves {defender} into the dye pack storage! {damage} damage and they're now bright purple!",
    ],
  },

  yellowcatz: {
    key: 'yellowcatz',
    name: 'YellowCatz',
    description: 'Cat degenerates in a neon alley war — meme-fueled chaos, claw combos, and zero chill.',
    exclusive: true,
    lobbyIcon: '🐱',
    joinEmoji: '🐾',
    lobbyColor: '#facc15',
    lobbyOpening: 'The alley lights flicker. The YellowCatz are locked in and feral.',
    lobbyJoinPrompt: 'React with 🐾 to join the alley brawl.',
    lobbyTitle: '🐾 YellowCatz Alley Lobby',
    lobbyFooter: 'Crew leader can /battle start when ready | Era: YellowCatz',
    lobbyPlayersLabel: '🐾 Degens',
    eliminationLines: [
      "💀 {defender} chased a laser pointer into live traffic. {attacker} didn’t even need to swing.",
      "💀 {defender} rage-typed mid-fight and got pounced by {attacker}. Priorities.",
      "💀 {defender} tried to hiss at {attacker}. {attacker} hissed louder and ended it.",
      "💀 {defender} got catnip-baited into a trap and folded instantly.",
      "💀 {attacker} pushed {defender} off the rooftop with one paw. Gravity did the rest.",
      "💀 {defender} slipped on spilled tuna oil while {attacker} watched politely.",
      "💀 {defender} tried to flex nine lives. Turns out they were already on the last one.",
      "💀 {attacker} zip-tied {defender} to a scratching post. Brutal but educational.",
      "💀 {defender} ran from {attacker} and face-planted into a dumpster lid.",
      "💀 {attacker} fake-meowed, {defender} looked away, and that was game over.",
      "💀 {defender} took a claw combo and uninstalled confidence.",
      "💀 {attacker} baited {defender} with lootbox crumbs. Classic degen punish.",
      "💀 {defender} jumped first, thought second, and landed wrong. {attacker} capitalized.",
      "💀 {defender} got boxed in between alley fences by {attacker}. No exits, no mercy.",
      "💀 {attacker} launched {defender} into a stack of pizza boxes. Structural failure.",
      "💀 {defender} tried stealth with a jingling collar. {attacker} heard everything.",
      "💀 {defender} challenged {attacker} to parkour. Lost at the first neon sign.",
      "💀 {attacker} pounced from a fire escape and deleted {defender}'s HP bar.",
      "💀 {defender} got distracted by a dangling shoelace. {attacker} does not forgive.",
      "💀 {attacker} swatted {defender} into a vending machine. Catastrophic snack incident.",
      "💀 {defender} said 'ez' too early. {attacker} took that personally.",
      "💀 {attacker} weaponized a cardboard box. {defender} never saw it coming.",
      "💀 {defender} took a direct hit from a tuna can and mentally checked out.",
      "💀 {attacker} juked left, clawed right, and ended {defender}'s career.",
      "💀 {defender} tried to bribe {attacker} with cheap kibble. Insulting and fatal.",
      "💀 {attacker} pulled the emergency ladder, and {defender} rode it down face-first.",
      "💀 {defender} got caught monologuing about alpha status. {attacker} skipped the speech.",
      "💀 {attacker} tagged {defender} with permanent marker: 'feed me'. Respect lost forever.",
      "💀 {defender} ignored alley code and got evicted by force.",
      "💀 {attacker} ended the duel with a spinning tail-whip from nowhere.",
    ],
    arrestLines: [
      "🚨 {defender} got scooped by animal control while {attacker} pointed from the shadows.",
      "🚨 {attacker} leaked {defender}'s location in guild chat. Cops arrived instantly.",
      "🚨 {defender} tried to flee in a shopping cart. Wheel lock engaged.",
      "🚨 {attacker} framed {defender} for scratching the mayor's car. Authorities believed it.",
      "🚨 {defender} hid in a laundry basket labeled 'not suspicious'. Very suspicious.",
      "🚨 {defender} got busted carrying contraband catnip in plain sight.",
      "🚨 {attacker} dropped a tip line call and waved as sirens rolled in.",
      "🚨 {defender} ran into a dead-end alley and negotiated with nobody.",
      "🚨 {attacker} baited {defender} under a net trap. Vintage alley tech.",
      "🚨 {defender} livestreamed the crime by accident. Evidence was excellent.",
      "🚨 {attacker} swapped {defender}'s getaway map with a menu. Arrest speedrun.",
      "🚨 {defender} got cuffed after trying to bluff with fake whisker credentials.",
      "🚨 {attacker} tagged {defender} with glow paint. Tracking was trivial.",
      "🚨 {defender} got caught arguing with a parking meter camera.",
    ],
    combatLines: [
      "{attacker} rakes {defender} with a five-claw combo for {damage} HP!",
      "{attacker} pounces from above and body-checks {defender}! {damage} damage!",
      "{attacker} smacks {defender} with a tuna can. {damage} HP and pure disrespect!",
      "{attacker} whip-cracks their tail across {defender}'s face! {damage} damage!",
      "{attacker} launches a neon bottle at {defender}. {damage} HP shattered!",
      "{attacker} claws through {defender}'s hoodie for {damage} damage!",
      "{attacker} blindside-tackles {defender} off a crate! {damage} HP!",
      "{attacker} spins and lands a double-paw strike on {defender}! {damage} damage!",
      "{attacker} feints with a hiss then uppercuts {defender}. {damage} HP!",
      "{attacker} sends {defender} sliding across wet pavement for {damage} damage!",
      "{attacker} dropkicks {defender} into a dumpster! {damage} HP!",
      "{attacker} shreds {defender} with alley-born precision. {damage} damage!",
      "{attacker} boomerangs a collar tag at {defender}! {damage} HP!",
      "{attacker} lands a spinning claw cyclone on {defender}. {damage} damage!",
      "{attacker} uses a metal lid as a shield-bash on {defender}! {damage} HP!",
      "{attacker} shoulder-checks {defender} into a brick wall. {damage} damage!",
      "{attacker} chain-combos {defender} with three clean swipes! {damage} HP!",
      "{attacker} elbows {defender} while yelling 'no naps in ranked!' {damage} damage!",
      "{attacker} throws a scratch-post splinter at {defender}. {damage} HP!",
      "{attacker} blitzes {defender} with feral speed for {damage} damage!",
    ],
    flavorLines: [
      "🐾 {player} sharpens their claws on a stolen speaker cabinet.",
      "😼 {player} practices their meanest alley stare in a puddle reflection.",
      "🧃 {player} steals an energy drink and immediately regrets nothing.",
      "🟨 {player} repaints a wall stripe in YellowCatz colors.",
      "📱 {player} checks the feed. Someone just called them 'mid'. Dangerous.",
      "🐟 {player} finds an old tuna tin and calls it a lucky charm.",
      "🎧 {player} nods to bass-heavy beats echoing through the alley.",
      "🧥 {player} flips up their hoodie and disappears into steam.",
      "🧠 {player} overthinks strategy for five seconds, then chooses chaos.",
      "🏙️ {player} climbs a fire escape for better battlefield vision.",
      "😾 {player} hisses at a drone camera until it backs off.",
      "💛 {player} tags a heart on the wall: 'Cats over everything'.",
      "🛹 {player} kickflips a board over a puddle and lands clean.",
      "🎯 {player} lines up angles like this is a speedrun.",
      "🍕 {player} steals a slice and calls it pre-fight fuel.",
      "🔦 {player} chases a red laser dot for one second. Just one.",
      "🧵 {player} untangles a collar charm and pockets it for luck.",
      "📻 {player} hears comms static: 'Stay feral, stay yellow.'",
      "🌧️ {player} watches rain bounce off neon signs and grins.",
      "🧤 {player} tightens fingerless gloves and cracks their wrists.",
      "🎮 {player} mutters: 'Ranked mentality. No mercy.'",
      "🚧 {player} drags a traffic cone into place as improvised cover.",
      "🪜 {player} tests a ladder rung. Still sketchy. Still usable.",
      "🗑️ {player} checks behind the dumpster for hidden supplies.",
      "🐱 {player} stretches like a predator before the next clash.",
      "💬 {player} sends one message: 'Pull up.'",
    ],
    eliteLines: [
      "🐱 ELITE FOUR: The fiercest YellowCatz degens claim the neon circle.",
      "🏆 Final alley showdown. Claws out, ego louder.",
    ],
    victoryLine: "👑 {winner} owns the alley tonight. Certified YellowCatz apex degen.",
  },

  medieval: {
    key: 'medieval',
    name: 'Medieval',
    description: 'Knights, castles, and swords — honor on the battlefield.',
    exclusive: false,
    lobbyIcon: '⚔️',
    lobbyColor: '#8B4513',
    lobbyOpening: 'Warriors gather at the castle gates. Only one shall claim the throne.',
    lobbyPlayersLabel: '⚔️ Warriors',
    eliminationLines: [
      "💀 {defender} was unseated in the joust and bounced into the moat.",
      "💀 {defender} challenged the Black Knight. Turns out it was just a flesh wound — for the Knight.",
      "💀 {defender} tried to outsmart the dragon. The dragon had better grades.",
      "💀 {defender} fell into the dungeon while looking for the dungeon.",
      "💀 {defender} got crushed by a trebuchet they were still adjusting.",
      "💀 {defender} ate suspicious mutton at the feast. The cook had loyalties.",
      "💀 {defender} wandered into the wrong jousting lane. Very wrong lane.",
      "💀 {defender} was betrayed by their squire. Squires remember everything.",
      "💀 {defender} forgot chainmail isn't a raincoat.",
      "💀 {defender} was knighted... in the wrong direction. By the wrong sword.",
      "💀 {defender} tried to parley. Nobody was in the mood.",
      "💀 {defender} got lost in the castle maze. Still technically lost.",
      "💀 {defender} called the king's court jester 'not that funny'. Fatal error.",
      "💀 {defender} spilled mead on the Duke's boots. The Duke had a long memory.",
      "💀 {defender} challenged a wizard to a duel of wits. The wizard cheated.",
    ],
    combatLines: [
      "{attacker} cleaves {defender} with a broadsword for {damage} HP!",
      "{attacker} fires an arrow true — {damage} damage to {defender}!",
      "{attacker} drives a lance through {defender}'s shield! {damage} HP lost!",
      "{attacker} catches {defender} with a war hammer blow! {damage} damage!",
      "{attacker} swings a morning star at {defender}! {damage} HP of medieval justice!",
      "{attacker} knocks {defender} off their horse! {damage} damage in the mud!",
      "{attacker} batters {defender} with a shield bash! {damage} HP!",
      "{attacker} slashes {defender} across the breastplate! {damage} damage — the dents are permanent.",
      "{attacker} hurls a throwing axe at {defender}! {damage} HP!",
      "{attacker} catches {defender} in a bear trap! {damage} damage and nowhere to run!",
    ],
    flavorLines: [
      "🏰 {player} surveys the battlefield from the battlements.",
      "🍺 {player} drains a flagon of ale and wipes their beard.",
      "📜 {player} consults an ancient scroll. It says 'fight harder.'",
      "🐴 {player} whispers encouragement to their destrier.",
      "🛡️ {player} polishes their shield. Their reflection looks nervous.",
      "🔥 {player} watches the torches flicker. The wind picks up.",
      "⚔️ {player} tests the edge of their blade. Sharp.",
      "🎺 {player} hears the herald's horn. The battle renews.",
      "🦅 {player} spots a falcon overhead. Good omen, probably.",
      "🗡️ {player} adjusts their gauntlets and cracks their knuckles.",
    ],
    eliteLines: [
      "⚔️ THE ELITE FOUR gather at the Round Table. Only one earns the crown!",
      "🏆 The final champions face each other under the castle banner!",
    ],
    victoryLine: "👑 {winner} claims the throne! Long live the champion of the realm!",
  },

  cyberpunk: {
    key: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon streets, neural hacks, and corpo warfare in 2089.',
    exclusive: false,
    lobbyIcon: '🤖',
    lobbyColor: '#00FFFF',
    lobbyOpening: 'Jack in. The grid is live. One netrunner walks out.',
    lobbyPlayersLabel: '🤖 Netrunners',
    eliminationLines: [
      "💀 {defender}'s neural implant got bricked by a sloppy ICE routine.",
      "💀 {defender} flatlined mid-hack. The server sent their condolences.",
      "💀 {defender} took a hyper-velocity round and disconnected permanently.",
      "💀 {defender}'s chrome arm malfunctioned at exactly the wrong moment.",
      "💀 {defender} ran a virus they wrote themselves. Classic.",
      "💀 {defender} got sold out to Arasaka for spare parts.",
      "💀 {defender} tried to ghost the grid. The grid noticed.",
      "💀 {defender} got flatlined in a black ICE encounter they totally underestimated.",
      "💀 {defender}'s backup drive was already full. No respawn.",
      "💀 {defender} picked up a data chip off the street. Always a trap.",
      "💀 {defender} cyber-psychosis finally hit. The solo took care of the rest.",
      "💀 {defender} trusted a fixer who was triple-crossing everyone.",
      "💀 {defender} forgot to update their anti-viral firmware. Basic.",
      "💀 {defender} walked into a corpo ambush wearing last decade's armor.",
      "💀 {defender} got their wetware remotely wiped. Messy.",
    ],
    combatLines: [
      "{attacker} jack-hammers {defender}'s firewall for {damage} HP!",
      "{attacker} pops a smartgun round through {defender}'s vest! {damage} damage!",
      "{attacker} deploys a combat drone on {defender}! {damage} HP of aerial destruction!",
      "{attacker} overloads {defender}'s neural link! {damage} damage straight to the brain!",
      "{attacker} slices {defender} with monofilament wire! {damage} HP! So clean.",
      "{attacker} activates sandevistan and blurs past {defender}! {damage} damage before they blink!",
      "{attacker} hits {defender} with EMP rounds! {damage} HP and all their chrome glitches!",
      "{attacker} launches a cyberware virus at {defender}! {damage} damage as their arms twitch!",
      "{attacker} wallhacks {defender}'s cover and opens fire! {damage} HP!",
      "{attacker} catches {defender} with a kerenzikov-boosted combo! {damage} damage, multiple hits!",
    ],
    flavorLines: [
      "🌆 {player} scans the neon skyline. Drones everywhere tonight.",
      "💊 {player} pops a neurostim. Focus sharpening.",
      "📡 {player} picks up encrypted chatter on the airwaves.",
      "🔌 {player} patches a coolant leak in their chrome arm.",
      "😎 {player} pulls down their AR visor. Grid overlay active.",
      "🚗 {player} watches a corpo AV scream overhead.",
      "🗡️ {player} charges their mantis blades. Click.",
      "💿 {player} runs a quick diagnostic. All systems nominal. For now.",
      "🤖 {player} bribes a spider bot to watch their back.",
      "🌧️ {player} stands in the acid rain. It's fine. Mostly.",
    ],
    eliteLines: [
      "🤖 ELITE FOUR: The top netrunners jack into the final node. One walks the grid alone.",
      "⚡ The corpo feeds are watching. Make it worth the bandwidth.",
    ],
    victoryLine: "💾 {winner} flatlines the competition. Legend of the net.",
  },

  wild_west: {
    key: 'wild_west',
    name: 'Wild West',
    description: 'High noon duels, bounty hunters, and frontier justice.',
    exclusive: false,
    lobbyIcon: '🤠',
    lobbyColor: '#DAA520',
    lobbyOpening: 'The saloon goes quiet. Boots on the floorboards. One sheriff leaves town standing.',
    lobbyPlayersLabel: '🤠 Gunslingers',
    eliminationLines: [
      "💀 {defender} drew second. Fractions matter out here.",
      "💀 {defender} rode into the canyon. Nobody told them about the ambush.",
      "💀 {defender} cheated at cards. The wrong table at the wrong time.",
      "💀 {defender} tried to outrun a horse on foot. Horses are fast.",
      "💀 {defender} mistook a rattlesnake for a rope. Common error.",
      "💀 {defender} bet their boots on a bad hand. Barefoot and gone.",
      "💀 {defender} challenged the wrong stranger to a duel at high noon.",
      "💀 {defender}'s six-shooter jammed. Their luck did too.",
      "💀 {defender} tried to rob the railroad. The railroad had Pinkertons.",
      "💀 {defender} talked too much in the wrong saloon. The piano stopped. Bad sign.",
      "💀 {defender} looked for a shortcut through Apache territory. Took it anyway.",
      "💀 {defender}'s wanted poster got an update. 'Deceased.'",
      "💀 {defender} underestimated the bounty hunter. Everyone does, once.",
      "💀 {defender} pulled iron slower than their shadow.",
      "💀 {defender} got bushwhacked at the waterhole. Never let your guard down in the desert.",
    ],
    combatLines: [
      "{attacker} fans the hammer and puts three into {defender}! {damage} HP!",
      "{attacker} draws from the hip and catches {defender} clean! {damage} damage!",
      "{attacker} wings {defender} off a ricochet! {damage} HP — lucky shot!",
      "{attacker} lassos {defender} and drags them through the dust! {damage} damage!",
      "{attacker} catches {defender} with a rifle shot from the ridge! {damage} HP!",
      "{attacker} pistol-whips {defender} with the butt of their Colt! {damage} damage!",
      "{attacker} throws a horseshoe at {defender}! {damage} HP! Unorthodox but effective.",
      "{attacker} rolls under a wagon and fires up at {defender}! {damage} damage!",
      "{attacker} drops {defender} with a boot knife to the thigh! {damage} HP! No fair!",
      "{attacker} fires through the saloon window at {defender}! {damage} damage! Glass everywhere!",
    ],
    flavorLines: [
      "🌵 {player} tips their hat and scans the horizon.",
      "🌅 {player} watches the sun hit the mesa. Beautiful, deadly country.",
      "🐎 {player} checks on their horse. Still there. Good.",
      "🎸 {player} hears a distant guitar. Getting closer.",
      "🪶 {player} reads the dust for tracks. Someone came through here recently.",
      "🔫 {player} spins the cylinder and checks their loads.",
      "🍺 {player} nurses a warm whiskey at the bar. Eyes on the door.",
      "🌪️ {player} sees a dust devil spin up across the flats.",
      "🃏 {player} shuffles a deck of cards. Old habit.",
      "👢 {player} digs a heel spur into the floorboards. Antsy.",
    ],
    eliteLines: [
      "🤠 HIGH NOON: The final four gunslingers face off on Main Street!",
      "🏆 The last chance saloon. One rides out of here a legend.",
    ],
    victoryLine: "🤠 {winner} holsters their iron. The town is safe. For now.",
  },

  space_age: {
    key: 'space_age',
    name: 'Space Age',
    description: 'Laser cannons, zero-G combat, and galactic conquest.',
    exclusive: false,
    lobbyIcon: '🚀',
    lobbyColor: '#1A1AFF',
    lobbyOpening: 'All crew to battle stations. One pilot exits this sector alive.',
    lobbyPlayersLabel: '🚀 Pilots',
    eliminationLines: [
      "💀 {defender} got sucked out of the airlock. Occupational hazard.",
      "💀 {defender} misread a wormhole as a shortcut. It was not a shortcut.",
      "💀 {defender} got clipped by a debris field traveling at 7 km/s.",
      "💀 {defender} trusted their shields at 1%. Shields were not enough.",
      "💀 {defender} ran out of fuel mid-dogfight. Very bad timing.",
      "💀 {defender} got caught in a tractor beam and never pulled out.",
      "💀 {defender} tried to fix the laser cannon while it was charging.",
      "💀 {defender} made first contact. It did not go well.",
      "💀 {defender} piloted into a nebula to hide. The nebula was inhabited.",
      "💀 {defender} forgot to wear their helmet. Space doesn't negotiate.",
      "💀 {defender} got their fighter sliced in half by a capital ship turret.",
      "💀 {defender} drifted into a black hole's event horizon. No U-turn.",
      "💀 {defender} ran a software update mid-combat. Auto-restart. Fatal.",
      "💀 {defender} was fragged by their own torpedo's splash radius.",
      "💀 {defender} tried to trade shots with a dreadnought. In a shuttle.",
    ],
    combatLines: [
      "{attacker} locks phase cannons on {defender} and fires! {damage} HP vaporized!",
      "{attacker} launches a missile spread at {defender}! {damage} damage — shields buckling!",
      "{attacker} rams {defender} in a zero-G broadside! {damage} HP!",
      "{attacker} fires a rail gun slug through {defender}'s hull! {damage} damage!",
      "{attacker} deploys a fighter drone swarm at {defender}! {damage} HP of coordinated chaos!",
      "{attacker} catches {defender} with a plasma burst! {damage} damage — systems offline!",
      "{attacker} activates stealth and stabs {defender} from behind! {damage} HP!",
      "{attacker} fires a gravity bomb at {defender}! {damage} damage! Physics wins again.",
      "{attacker} clips {defender}'s engine pod! {damage} HP and they're spinning!",
      "{attacker} hits {defender} with a focused EMP burst! {damage} damage — everything glitches!",
    ],
    flavorLines: [
      "🌌 {player} stares into the void. The void seems interested.",
      "🛸 {player} spots an unidentified blip on the long-range scanner.",
      "⭐ {player} navigates by starlight. Old school.",
      "🔭 {player} pulls up a star chart. Something's not right.",
      "🛰️ {player} reroutes power from life support to weapons. Bold choice.",
      "👽 {player} receives a transmission in a language they don't recognize. Unsettling.",
      "🚀 {player} burns thrusters to gain altitude. Above the debris field now.",
      "💫 {player} watches a distant supernova light up the sector.",
      "🎮 {player} calibrates targeting systems. Lock and load.",
      "🌙 {player} drifts past a dead moon. Quiet out here. Too quiet.",
    ],
    eliteLines: [
      "🚀 FINAL FOUR: The last fighters converge on the space station. One leaves the sector.",
      "⭐ The galaxy watches. Make history.",
    ],
    victoryLine: "🌌 {winner} achieves total orbital supremacy. Galactic champion!",
  },
};

module.exports = { BATTLE_ERAS };
