/**
 * Battle era configurations.
 * Each era defines themed text lines used during battle simulation.
 * The "mafia" era is the default and always available.
 * Exclusive eras require superadmin assignment to a guild.
 */

const BATTLE_ERAS = {
  mafia: {
    key: 'mafia',
    name: 'Mafia',
    description: 'Classic Syndicate mafia warfare — concrete shoes, cannoli, and family honor.',
    exclusive: false,
    lobbyIcon: '⚔️',
    lobbyColor: '#FFD700',
    lobbyOpening: 'The family is gathering for a showdown.',
    lobbyPlayersLabel: '🥊 Fighters',
    eliminationLines: [
      "☠️ {defender} has been iced. Room temperature.",
      "☠️ {defender} sleeps with the fishes now.",
      "☠️ {defender} got clipped. It's nothing personal, just business.",
      "☠️ {defender} won't be coming back from this one.",
      "☠️ {defender} got whacked. Say goodnight.",
      "☠️ {defender} slipped on a banana peel into a cement mixer. Classic.",
      "☠️ {defender} confused the espresso machine with a tommy gun. Fatal mistake.",
      "☠️ {defender} tried to outrun a horse. The horse won.",
      "☠️ {defender} ate the cannoli that was DEFINITELY poisoned.",
      "☠️ {defender} took a nap in the wrong trunk. Permanent nap.",
      "☠️ {defender} challenged the boss to poker. Lost everything. Including their life.",
      "☠️ {defender} got locked in the walk-in freezer. Very chilly farewell.",
      "☠️ {defender} mistook dynamite for a cigar. Explosive exit.",
      "☠️ {defender} tried to skip out on a tab at Luigi's. Luigi doesn't forget.",
      "☠️ {defender} insulted someone's mother. The streets are ruthless.",
      "☠️ {defender} walked into the wrong social club. Very wrong.",
      "☠️ {defender} bet against the family. Bad investment.",
      "☠️ {defender} forgot to pay respects. The family remembered.",
      "☠️ {defender} accidentally sat in the boss's chair. Last mistake ever.",
      "☠️ {defender} tried to rob the mafia piggy bank. Piggy fought back.",
      "☠️ {defender} talked to the feds. The family talked back.",
      "☠️ {defender} laughed at the wrong joke. The punchline was lethal.",
      "☠️ {defender} thought they could swim faster than the concrete. They couldn't.",
      "☠️ {defender} ordered pineapple on pizza at the family dinner. Unforgivable.",
      "☠️ {defender} tried to count cards at Tony's poker night. Tony counted them out.",
      "☠️ {defender} showed up late to a hit. Irony got them first.",
      "☠️ {defender} opened an umbrella indoors. Superstition killed them.",
      "☠️ {defender} spilled wine on the tablecloth. The family spilled their blood.",
      "☠️ {defender} forgot the boss's birthday. The boss didn't forget them.",
      "☠️ {defender} tried to parallel park the getaway car. Still parked there. Forever.",
    ],
    combatLines: [
      "{attacker} sends {defender} to sleep with the fishes for {damage} HP!",
      "{attacker} delivers an offer {defender} can't refuse - {damage} damage!",
      "{attacker} whacks {defender} with a tire iron for {damage} HP!",
      "{attacker} gives {defender} a concrete shoe fitting - {damage} damage!",
      "{attacker} breaks {defender}'s kneecaps for {damage} HP!",
      "{attacker} puts a hit on {defender} - {damage} damage taken!",
      "{attacker} makes {defender} kiss the ring... with their face! {damage} HP!",
      "{attacker} pistol-whips {defender} for {damage} damage!",
      "{attacker} sends {defender} a message - {damage} HP worth!",
      "{attacker} shows {defender} who's boss - {damage} damage!",
      "{attacker} throws {defender} through a window! {damage} HP shattered!",
      "{attacker} introduces {defender} to their baseball bat! {damage} damage!",
    ],
    flavorLines: [
      "🚬 {player} lights up a cigar and contemplates life.",
      "📞 {player} gets a call from the boss. 'Keep it clean.'",
      "🎰 {player} checks the numbers from last night's game.",
      "🚗 {player} hears sirens in the distance. Feds getting close.",
      "🎵 {player} hums 'That's Amore' while reloading.",
      "💼 {player} checks the briefcase. Everything's there.",
      "🍷 {player} swirls a glass of expensive wine.",
      "🕊️ {player} feeds the pigeons. Even killers have hobbies.",
      "🎭 {player} practices their alibi in the mirror.",
      "🌃 {player} admires the skyline. Beautiful city. Violent, but beautiful.",
      "🔫 {player} cleans their gun. Maintenance is important.",
      "📰 {player} reads the obituaries. Checking for friends.",
      "🎪 {player} juggles grenades. Just kidding. Or are they?",
      "🚪 {player} checks the exits. Always have an escape plan.",
      "👔 {player} adjusts their tie. Looking sharp for the funeral. Theirs? Who knows.",
      "🎬 {player} quotes The Godfather. Classic move.",
      "🍝 {player} debates opening a legitimate restaurant. Nah.",
      "💰 {player} counts money nervously. Is it all there?",
      "🚕 {player} hails a cab. Wait, that's not a cab driver...",
      "🎲 {player} rolls dice on the ground. Snake eyes. Bad omen.",
      "📱 {player} checks their burner phone. 47 missed calls from mom.",
      "🏪 {player} window-shops at the corner store. Maybe they'll rob it later.",
      "⛪ {player} says a quick prayer. Insurance policy.",
      "🎺 {player} hears jazz in the distance. Classy.",
      "🌹 {player} smells a rose. Then sneezes violently.",
      "🚬 {player} offers someone a cigarette. Declined. Rude.",
      "🎩 {player} tips their fedora at a passing stranger.",
      "🍕 {player} debates pineapple on pizza. Decides against it. Smart.",
      "🔮 {player} visits a fortune teller. 'I see violence.' No kidding.",
      "🎸 {player} air-guitars to Frank Sinatra. Embarrassing.",
    ],
  },

  vault_runners: {
    key: 'vault_runners',
    name: 'Vault Runners',
    description: 'Incompetent criminals pulling a heist. Ocean\'s Eleven meets Arrested Development.',
    exclusive: true,
    lobbyIcon: '🏦',
    lobbyColor: '#22c55e',
    lobbyOpening: 'The crew is assembling. Someone remembered the drill this time. Probably.',
    lobbyPlayersLabel: '🦹 The Crew',
    eliminationLines: [
      "💀 {defender} triggered the alarm by sneezing into the motion sensor. {attacker} shoved them into the laser grid on the way out.",
      "💀 {attacker} \"accidentally\" closed the vault door on {defender}. The time lock is set for 72 hours. Good luck in there.",
      "💀 {defender} got tangled in their own grappling hook and {attacker} just... watched. Popcorn and everything.",
      "💀 {attacker} swapped {defender}'s smoke bomb with a flashbang. {defender} is now blind AND arrested.",
      "💀 {defender} tried to crawl through the air vent. Got stuck at the first turn. {attacker} sealed it shut.",
      "💀 {attacker} told {defender} the getaway car was in Lot B. There is no Lot B. {defender} is still looking.",
      "💀 {defender}'s disguise was a name tag that said 'NOT A CRIMINAL.' Security disagreed. {attacker} waved goodbye.",
      "💀 {attacker} used {defender} as a human shield when the security guard dog showed up. The dog chose violence.",
      "💀 {defender} accidentally called 911 instead of the crew's burner. Gave their full name and location. {attacker} is already in the car.",
      "💀 {attacker} convinced {defender} the vault combination was their birthday. It wasn't. The alarm was loud.",
      "💀 {defender} left fingerprints on EVERYTHING including the 'Please Do Not Touch' sign. {attacker} tipped off forensics for fun.",
      "💀 {defender}'s flashlight batteries died at the worst possible moment. {attacker}'s didn't. Nature selected.",
      "💀 {attacker} told {defender} to \"hold this\" and handed them a dye pack. Three... two... one... purple.",
      "💀 {defender} wore squeaky shoes to a stealth heist. {attacker} heard them from three floors away. So did everyone else.",
      "💀 {attacker} reprogrammed the signal jammer to only jam {defender}'s radio. {defender} has been talking to nobody for twenty minutes.",
      "💀 {defender} grabbed what they thought was the diamond. It was a paperweight from the gift shop. {attacker} has the real one.",
      "💀 {defender} tried to hack the security system by typing 'password123'. It worked. Then {attacker} changed it.",
    ],
    arrestLines: [
      "🚔 {defender} got tackled by a security guard who was honestly just having a really bad day. {attacker} filmed it.",
      "🚔 {attacker} anonymously reported {defender}'s location to the cops. From ten feet away. While waving.",
      "🚔 {defender} tried to bribe the guard with Monopoly money. The guard was not amused. {attacker} provided the handcuffs.",
      "🚔 {defender} ran straight into a glass door trying to escape. Left a face print. {attacker} signed it as modern art.",
      "🚔 {defender} hid in a storage closet. It was the security office. {attacker} locked it from outside.",
      "🚔 The K-9 unit found {defender} because they had bacon in their pocket. WHY did they have bacon? {attacker} knows why.",
      "🚔 {defender} tried to blend in with the mannequins. Blinked. {attacker} yelled 'THAT ONE MOVED!' Very helpful.",
      "🚔 {defender} was caught because their getaway vehicle was a shopping cart. {attacker} popped the wheels earlier.",
      "🚔 {defender} surrendered after the security guard's walkie-talkie static scared them. {attacker} made the static noise.",
      "🚔 {defender} got arrested for trespassing, breaking and entering, AND an overdue library book. {attacker} planted the book.",
    ],
    flavorLines: [
      "🔦 {player} realizes their night-vision goggles are actually swim goggles painted black.",
      "📻 {player}'s earpiece starts picking up a local jazz station. They vibe for a second. Focus.",
      "🧤 {player} puts on their heist gloves. They're oven mitts. Close enough.",
      "🚗 {player} checks on the getaway car. It has a boot on it. That's new.",
      "🗺️ {player} unfolds the blueprint. It's upside down. Has been this whole time.",
      "💡 {player} accidentally triggers a hallway light. Freezes like a deer. Nobody noticed. Maybe.",
      "🎭 {player} adjusts their ski mask. It's on backwards. They can smell their own breath.",
      "📱 {player}'s phone goes off. The ringtone is the Mission Impossible theme. Irony is dead.",
      "🔑 {player} picks a lock in 3 seconds. Wrong door. That's a broom closet.",
      "🐕 {player} hears the security dog barking. Throws a steak. It's frozen solid. The dog is confused.",
      "💎 {player} spots the target vault. It's smaller than expected. Also it might be a safe deposit box.",
      "🧱 {player} tries to cut through a wall. Hits a water pipe. The heist is now also a pool party.",
      "🚨 {player} walks through a metal detector they didn't see. Everything beeps. Even their belt.",
      "📹 {player} waves at a security camera. Realizes. Puts hand down slowly. Damage done.",
      "🧊 {player} slips on a freshly mopped floor. The janitor watches. Judges silently.",
      "🎒 {player} opens their heist bag. It's full of sandwiches. Wrong bag. But honestly, needed those.",
      "🔧 {player} assembles the drill. Three parts are left over. That can't be good.",
      "🚪 {player} tries to open a push door by pulling. For thirty seconds. The camera got all of it.",
      "💨 {player} uses a smoke bomb for cover. In a room with smoke detectors. Sprinklers activate.",
      "🎵 {player} starts humming the heist music. The crew tells them to shut up. They hum quieter.",
      "🧲 {player} brought a magnet to disable the electronic lock. It disabled their own phone instead.",
      "📦 {player} hides behind a cardboard box. Metal Gear style. A guard kicks it. {player} says 'ow.'",
    ],
    combatLines: [
      "{attacker} throws a bag of stolen jewels at {defender}'s face! {damage} damage and a lot of scattered diamonds!",
      "{attacker} swings a gold bar at {defender}! {damage} HP of premium damage!",
      "{attacker} shoves {defender} into the laser grid! {damage} HP and a very geometric sunburn!",
      "{attacker} drops a ceiling tile on {defender} from the air vent! {damage} damage! Stealth: failed.",
      "{attacker} hits {defender} with a fire extinguisher! {damage} HP! Safety first, violence second.",
      "{attacker} throws a flash drive full of evidence at {defender}! {damage} damage! That's... not how you destroy evidence.",
      "{attacker} trips {defender} with a grappling hook! {damage} HP! Multi-purpose tool.",
      "{attacker} slams {defender} with a vault door! {damage} damage! That's gonna need some ice. And a chiropractor.",
      "{attacker} blinds {defender} with a laser pointer and kicks them down the stairs! {damage} HP!",
      "{attacker} releases the security dog on {defender}! {damage} damage! Bad dog. Good chaos.",
      "{attacker} hits {defender} with a duffle bag full of cash! {damage} HP! Most expensive punch ever.",
      "{attacker} shoves {defender} into the dye pack storage! {damage} damage and they're now bright purple!",
    ],
  },

  yellowcatz: {
    key: 'yellowcatz',
    name: 'YellowCatz',
    description: 'Pure YellowCatz chaos: alley tags, degen instincts, and claw-first street dominance.',
    exclusive: true,
    lobbyIcon: '🐱',
    joinEmoji: '🐾',
    lobbyColor: '#facc15',
    lobbyOpening: 'Graffiti drips, bass rattles, and the YellowCatz circle closes in.',
    lobbyJoinPrompt: 'React with 🐾 to rep YellowCatz and jump in.',
    lobbyTitle: '🐾 YellowCatz Alley Lobby',
    lobbyFooter: 'Pack leader can /battle start when ready | YellowCatz rules apply',
    lobbyPlayersLabel: '🐾 Alley Catz',
    victoryTitle: '💛 YellowCatz Block Winner',
    victoryFooter: 'Block secured • Claws clean • YellowCatz on top',
    victoryAnnouncement: '🐾 Alley belongs to {winnerMention}. YellowCatz takes the night.',
    eliminationLines: [
      "💀 {defender} missed a rooftop transfer and {attacker} claimed the lane below.",
      "💀 {attacker} ran a fake retreat, then snapped back and erased {defender}.",
      "💀 {defender} paused to taunt and {attacker} answered with instant claws.",
      "💀 {attacker} baited {defender} with a glowing toy drone and closed the trap.",
      "💀 {defender} got cornered between yellow-tagged walls and folded under pressure.",
      "💀 {attacker} shoulder-checked {defender} off the stair rail into the alley pit.",
      "💀 {defender} trusted the wrong shortcut; {attacker} was waiting at the choke point.",
      "💀 {attacker} knocked {defender} into a stack of delivery crates. Match done.",
      "💀 {defender} overcommitted on a leap and {attacker} punished the landing.",
      "💀 {attacker} clipped {defender} with a back-tail sweep and finished clean.",
      "💀 {defender} got tunnel vision on loot while {attacker} took the objective and the fight.",
      "💀 {attacker} dragged {defender} into a paint-slick lane. No traction, no chance.",
      "💀 {defender} tried to fake confidence; {attacker} read it and broke through.",
      "💀 {attacker} hit the wall-run angle and dropped directly onto {defender}.",
      "💀 {defender} challenged the pack leader and got removed from the alley roster.",
      "💀 {attacker} turned a metal sign into a launch ramp and sent {defender} flying.",
      "💀 {defender} mistimed the dodge by one beat; {attacker} never misses those.",
      "💀 {attacker} boxed {defender} against the shutter door and ended it fast.",
      "💀 {defender} burned all stamina sprinting; {attacker} collected the free finish.",
      "💀 {attacker} feinted low, struck high, and {defender} never recovered.",
      "💀 {defender} forgot the alley code and got executed by YellowCatz justice.",
      "💀 {attacker} used the neon flicker for cover and ambushed {defender} cold.",
      "💀 {defender} slipped on rain-slick concrete and {attacker} capitalized instantly.",
      "💀 {attacker} baited a chase through scaffolding and dropped {defender} at the exit.",
      "💀 {defender} got caught peeking the same corner twice. {attacker} punished both.",
      "💀 {attacker} shattered {defender}'s composure with one ruthless combo route.",
      "💀 {defender} tried to buy time; {attacker} sold speed and closed the deal.",
      "💀 {attacker} snapped a perfect alley line and deleted {defender} from the map.",
      "💀 {defender} went for highlight play, {attacker} went for the win.",
      "💀 {attacker} sealed the duel with a final pounce under the YellowCatz tag.",
    ],
    arrestLines: [
      "🚨 {attacker} pinged alley patrol with {defender}'s exact route. Intercepted.",
      "🚨 {defender} sprinted into a fenced cul-de-sac and stalled out.",
      "🚨 {attacker} sold {defender}'s hideout pin for one can of tuna.",
      "🚨 {defender} got grabbed by code enforcement for illegal rooftop access.",
      "🚨 {attacker} baited {defender} under a dropping shutter. Caught on site.",
      "🚨 {defender} triggered three cameras in ten seconds. Public record now.",
      "🚨 {attacker} swapped comm channels and left {defender} calling empty air.",
      "🚨 {defender} got traced by their own loudspeaker taunts.",
      "🚨 {attacker} painted an arrow to {defender}; patrol followed it perfectly.",
      "🚨 {defender} froze at a checkpoint and lost the bluff battle.",
      "🚨 {attacker} pushed false loot intel; {defender} walked into a sweep team.",
      "🚨 {defender} hid in plain sight wearing full YellowCatz colors. Bold and wrong.",
      "🚨 {attacker} dropped a burner tip that turned into instant cuffs for {defender}.",
      "🚨 {defender} got stopped while hauling suspiciously heavy catnip bags.",
    ],
    combatLines: [
      "{attacker} carves a diagonal claw route through {defender} for {damage} HP!",
      "{attacker} vaults a crate and lands both paws on {defender}! {damage} damage!",
      "{attacker} head-fakes left, tail-flicks right, and clips {defender} for {damage} HP!",
      "{attacker} slams {defender} into a tagged wall. {damage} damage and paint everywhere!",
      "{attacker} chains three alley swipes into {defender} for {damage} HP!",
      "{attacker} spins off a railing and smashes {defender} with a dive hit! {damage} damage!",
      "{attacker} shoulder-bursts through {defender}'s guard for {damage} HP!",
      "{attacker} launches a can lid ricochet at {defender}! {damage} damage!",
      "{attacker} catches {defender} mid-step with a low sweep. {damage} HP!",
      "{attacker} hammers {defender} with a rapid paw flurry for {damage} damage!",
      "{attacker} grabs high ground and drops onto {defender}. {damage} HP gone!",
      "{attacker} body-checks {defender} across the rain-slick lane for {damage} damage!",
      "{attacker} snap-kicks {defender} into scaffolding! {damage} HP!",
      "{attacker} rips through {defender}'s defense with feral tempo. {damage} damage!",
      "{attacker} feints retreat, pivots, and lands clean on {defender}. {damage} HP!",
      "{attacker} uses a street sign as a battering ram against {defender}! {damage} damage!",
      "{attacker} wall-runs and cross-slashes {defender} for {damage} HP!",
      "{attacker} hisses, lunges, and breaks {defender}'s rhythm for {damage} damage!",
      "{attacker} clips {defender}'s ankles then follows with an upper swipe. {damage} HP!",
      "{attacker} unloads peak YellowCatz pressure and crushes {defender} for {damage} damage!",
    ],
    critLines: [
      "{attacker} lands a perfect alley finisher on {defender}! CRITICAL {damage} damage!",
      "{attacker} reads {defender}'s movement and detonates a crit combo! {damage}!",
      "{attacker} snaps into feral mode and deletes {defender}'s guard! CRIT {damage}!",
      "{attacker} turns one opening into total punishment on {defender}! {damage} critical!",
      "{attacker} unloads peak YellowCatz mechanics on {defender}! CRITICAL {damage}!",
      "{attacker} wall-runs into a brutal crit strike on {defender}! {damage}!",
    ],
    itemLines: [
      "💛 {player} grabs a YellowCatz stim patch! (+12 HP)",
      "🐟 {player} downs premium tuna fuel! (+14 HP)",
      "🛡️ {player} straps on reinforced claw guards! (+16 HP)",
      "🧪 {player} uses alley med-gel and resets! (+11 HP)",
      "🔋 {player} taps a power cache and recovers! (+13 HP)",
      "🎯 {player} calibrates hunt vision! (Damage +20% next round)",
      "⚡ {player} overclocks their reflex chain! (Damage +20% next round)",
      "🧠 {player} locks into degen focus! (Damage +20% next round)",
      "🐾 {player} enters predator stance! (Damage +20% next round)",
      "🛠️ {player} hotfixes their kit mid-fight! (+10 HP)",
    ],
    tauntLines: [
      "💬 {attacker} to {defender}: \"This block runs yellow now.\"",
      "💬 {attacker} mocks {defender}: \"You're not built for alley pace.\"",
      "💬 {attacker} smirks: \"You brought noise. I brought control.\"",
      "💬 {attacker} tells {defender}: \"Wrong corner, wrong cat.\"",
      "💬 {attacker} laughs: \"You keep guessing. I keep landing.\"",
    ],
    trashTalkLines: [
      "🗣️ {attacker}: \"That's lane ownership, learn it.\"",
      "🗣️ {attacker} to {defender}: \"YellowCatz pressure never lets up.\"",
      "🗣️ {attacker}: \"Every trade favors me now.\"",
      "🗣️ {attacker} grins: \"You're reacting to my tempo.\"",
      "🗣️ {attacker}: \"One more mistake and you're off this block.\"",
    ],
    dodgeLines: [
      "⚡ {player} slips under {opponent}'s strike and resets center lane!",
      "🐾 {opponent} commits too hard; {player} sidesteps cleanly!",
      "💨 {player} vanishes into steam and {opponent} whiffs!",
      "🎯 {player} reads {opponent} perfectly and dodges at the last beat!",
      "🛡️ {player} pivots out of danger and keeps control!",
    ],
    comebackLines: [
      "🔥 {player} digs in and claws momentum back!",
      "💛 {player} refuses collapse and surges into a comeback!",
      "⚔️ {player} re-centers, re-times, and reclaims the fight!",
      "🧠 {player} adapts instantly and flips pressure onto {opponent}!",
      "🐱 {player} shakes off damage and hunts again!",
    ],
    roundTransitionLines: [
      "📢 Yellow lane reset. Round {round} starts now.",
      "🔔 Round {round}: claws up, eyes open, no hesitation.",
      "⚡ Round {round} loads in. Control the block or lose it.",
      "🎬 Round {round} begins under full neon pressure.",
      "🐾 Round {round}: YellowCatz pace goes up another level.",
    ],
    luckyEscapeLines: [
      "🍀 {player} survives by a whisker and stays in the alley war!",
      "✨ {player} hangs on at 1 HP. Unreal clutch.",
      "🐾 {player} refuses the fade and claws back to life!",
      "💛 {player} catches a miracle break and keeps fighting!",
      "⚡ {player} slips elimination with pure instinct!",
    ],
    flavorLines: [
      "🐾 {player} traces fresh YellowCatz tags and maps the control lanes.",
      "😼 {player} calibrates their stare in a puddle until it looks illegal.",
      "🎧 {player} syncs movement to a dirty bassline echoing through the block.",
      "🟨 {player} repaints a faded emblem brighter than the streetlights.",
      "📱 {player} checks the feed and smiles at the disrespect in the comments.",
      "🐟 {player} pockets a tuna charm before stepping into the circle.",
      "🧥 {player} tucks their hoodie and fades into steam at the corner.",
      "🏙️ {player} climbs a fire escape to scout every entry route.",
      "🧠 {player} rehearses five plans, then chooses the wild sixth.",
      "💛 {player} redraws a YellowCatz crown over rival graffiti.",
      "🛹 {player} uses a board to cross the slick lane without losing speed.",
      "🎯 {player} marks two blind spots and one perfect ambush angle.",
      "🍕 {player} steals half a slice and calls it macro optimization.",
      "🌧️ {player} times the neon flicker with the rain to mask movement.",
      "🧤 {player} tightens wraps and flexes their claws against the brick.",
      "🔊 {player} bumps volume just enough to shake loose rooftop pigeons.",
      "🧵 {player} reties a collar knot like a pre-fight ritual.",
      "📻 {player} hears: 'Pack up. Play sharp. Keep it yellow.'",
      "🚧 {player} shifts street clutter into a perfect funnel trap.",
      "🪜 {player} tests a ladder rung and trusts it anyway.",
      "🗑️ {player} checks the dumpster cache for spare gear and surprises.",
      "🐱 {player} stretches low, tail steady, eyes locked on the lane.",
      "💬 {player} posts one line: 'YellowCatz online.'",
      "⚡ {player} taps a buzzing sign and grins at the static pop.",
      "🎮 {player} mutters: 'No tilt. No mercy. Full degen mode.'",
      "🚦 {player} watches the traffic cycle and predicts the next window.",
    ],
    eliteLines: [
      "🐾 ELITE FOUR: The sharpest YellowCatz names step into the neon killbox.",
      "🏆 Last circle in the alley. No backups, no brakes, no fear.",
    ],
    finaleOutros: [
      "{winner} locked the lane and walked out owning the block after {rounds} rounds.",
      "{totalPlayers} came in loud, but {winner} finished louder. YellowCatz certified.",
      "{winner} turned alley pressure into a clean takeover. Crown secured.",
      "When the paint dried and the rain stopped, only {winner} remained.",
      "{winner} out-read every angle and closed the match like a true YellowCatz closer.",
      "No backup needed: {winner} held the line and took full control of the block.",
    ],
    victoryLine: "👑 {winner} takes the block and the bragging rights. YellowCatz legend confirmed.",
  },

  medieval: {
    key: 'medieval',
    name: 'Medieval',
    description: 'Knights, castles, and swords — honor on the battlefield.',
    exclusive: false,
    lobbyIcon: '⚔️',
    lobbyColor: '#8B4513',
    lobbyOpening: 'Warriors gather at the castle gates. Only one shall claim the throne.',
    lobbyPlayersLabel: '⚔️ Warriors',
    eliminationLines: [
      "💀 {defender} was unseated in the joust and bounced into the moat.",
      "💀 {defender} challenged the Black Knight. Turns out it was just a flesh wound — for the Knight.",
      "💀 {defender} tried to outsmart the dragon. The dragon had better grades.",
      "💀 {defender} fell into the dungeon while looking for the dungeon.",
      "💀 {defender} got crushed by a trebuchet they were still adjusting.",
      "💀 {defender} ate suspicious mutton at the feast. The cook had loyalties.",
      "💀 {defender} wandered into the wrong jousting lane. Very wrong lane.",
      "💀 {defender} was betrayed by their squire. Squires remember everything.",
      "💀 {defender} forgot chainmail isn't a raincoat.",
      "💀 {defender} was knighted... in the wrong direction. By the wrong sword.",
      "💀 {defender} tried to parley. Nobody was in the mood.",
      "💀 {defender} got lost in the castle maze. Still technically lost.",
      "💀 {defender} called the king's court jester 'not that funny'. Fatal error.",
      "💀 {defender} spilled mead on the Duke's boots. The Duke had a long memory.",
      "💀 {defender} challenged a wizard to a duel of wits. The wizard cheated.",
    ],
    combatLines: [
      "{attacker} cleaves {defender} with a broadsword for {damage} HP!",
      "{attacker} fires an arrow true — {damage} damage to {defender}!",
      "{attacker} drives a lance through {defender}'s shield! {damage} HP lost!",
      "{attacker} catches {defender} with a war hammer blow! {damage} damage!",
      "{attacker} swings a morning star at {defender}! {damage} HP of medieval justice!",
      "{attacker} knocks {defender} off their horse! {damage} damage in the mud!",
      "{attacker} batters {defender} with a shield bash! {damage} HP!",
      "{attacker} slashes {defender} across the breastplate! {damage} damage — the dents are permanent.",
      "{attacker} hurls a throwing axe at {defender}! {damage} HP!",
      "{attacker} catches {defender} in a bear trap! {damage} damage and nowhere to run!",
    ],
    flavorLines: [
      "🏰 {player} surveys the battlefield from the battlements.",
      "🍺 {player} drains a flagon of ale and wipes their beard.",
      "📜 {player} consults an ancient scroll. It says 'fight harder.'",
      "🐴 {player} whispers encouragement to their destrier.",
      "🛡️ {player} polishes their shield. Their reflection looks nervous.",
      "🔥 {player} watches the torches flicker. The wind picks up.",
      "⚔️ {player} tests the edge of their blade. Sharp.",
      "🎺 {player} hears the herald's horn. The battle renews.",
      "🦅 {player} spots a falcon overhead. Good omen, probably.",
      "🗡️ {player} adjusts their gauntlets and cracks their knuckles.",
    ],
    eliteLines: [
      "⚔️ THE ELITE FOUR gather at the Round Table. Only one earns the crown!",
      "🏆 The final champions face each other under the castle banner!",
    ],
    victoryLine: "👑 {winner} claims the throne! Long live the champion of the realm!",
  },

  cyberpunk: {
    key: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon streets, neural hacks, and corpo warfare in 2089.',
    exclusive: false,
    lobbyIcon: '🤖',
    lobbyColor: '#00FFFF',
    lobbyOpening: 'Jack in. The grid is live. One netrunner walks out.',
    lobbyPlayersLabel: '🤖 Netrunners',
    eliminationLines: [
      "💀 {defender}'s neural implant got bricked by a sloppy ICE routine.",
      "💀 {defender} flatlined mid-hack. The server sent their condolences.",
      "💀 {defender} took a hyper-velocity round and disconnected permanently.",
      "💀 {defender}'s chrome arm malfunctioned at exactly the wrong moment.",
      "💀 {defender} ran a virus they wrote themselves. Classic.",
      "💀 {defender} got sold out to Arasaka for spare parts.",
      "💀 {defender} tried to ghost the grid. The grid noticed.",
      "💀 {defender} got flatlined in a black ICE encounter they totally underestimated.",
      "💀 {defender}'s backup drive was already full. No respawn.",
      "💀 {defender} picked up a data chip off the street. Always a trap.",
      "💀 {defender} cyber-psychosis finally hit. The solo took care of the rest.",
      "💀 {defender} trusted a fixer who was triple-crossing everyone.",
      "💀 {defender} forgot to update their anti-viral firmware. Basic.",
      "💀 {defender} walked into a corpo ambush wearing last decade's armor.",
      "💀 {defender} got their wetware remotely wiped. Messy.",
    ],
    combatLines: [
      "{attacker} jack-hammers {defender}'s firewall for {damage} HP!",
      "{attacker} pops a smartgun round through {defender}'s vest! {damage} damage!",
      "{attacker} deploys a combat drone on {defender}! {damage} HP of aerial destruction!",
      "{attacker} overloads {defender}'s neural link! {damage} damage straight to the brain!",
      "{attacker} slices {defender} with monofilament wire! {damage} HP! So clean.",
      "{attacker} activates sandevistan and blurs past {defender}! {damage} damage before they blink!",
      "{attacker} hits {defender} with EMP rounds! {damage} HP and all their chrome glitches!",
      "{attacker} launches a cyberware virus at {defender}! {damage} damage as their arms twitch!",
      "{attacker} wallhacks {defender}'s cover and opens fire! {damage} HP!",
      "{attacker} catches {defender} with a kerenzikov-boosted combo! {damage} damage, multiple hits!",
    ],
    flavorLines: [
      "🌆 {player} scans the neon skyline. Drones everywhere tonight.",
      "💊 {player} pops a neurostim. Focus sharpening.",
      "📡 {player} picks up encrypted chatter on the airwaves.",
      "🔌 {player} patches a coolant leak in their chrome arm.",
      "😎 {player} pulls down their AR visor. Grid overlay active.",
      "🚗 {player} watches a corpo AV scream overhead.",
      "🗡️ {player} charges their mantis blades. Click.",
      "💿 {player} runs a quick diagnostic. All systems nominal. For now.",
      "🤖 {player} bribes a spider bot to watch their back.",
      "🌧️ {player} stands in the acid rain. It's fine. Mostly.",
    ],
    eliteLines: [
      "🤖 ELITE FOUR: The top netrunners jack into the final node. One walks the grid alone.",
      "⚡ The corpo feeds are watching. Make it worth the bandwidth.",
    ],
    victoryLine: "💾 {winner} flatlines the competition. Legend of the net.",
  },

  wild_west: {
    key: 'wild_west',
    name: 'Wild West',
    description: 'High noon duels, bounty hunters, and frontier justice.',
    exclusive: false,
    lobbyIcon: '🤠',
    lobbyColor: '#DAA520',
    lobbyOpening: 'The saloon goes quiet. Boots on the floorboards. One sheriff leaves town standing.',
    lobbyPlayersLabel: '🤠 Gunslingers',
    eliminationLines: [
      "💀 {defender} drew second. Fractions matter out here.",
      "💀 {defender} rode into the canyon. Nobody told them about the ambush.",
      "💀 {defender} cheated at cards. The wrong table at the wrong time.",
      "💀 {defender} tried to outrun a horse on foot. Horses are fast.",
      "💀 {defender} mistook a rattlesnake for a rope. Common error.",
      "💀 {defender} bet their boots on a bad hand. Barefoot and gone.",
      "💀 {defender} challenged the wrong stranger to a duel at high noon.",
      "💀 {defender}'s six-shooter jammed. Their luck did too.",
      "💀 {defender} tried to rob the railroad. The railroad had Pinkertons.",
      "💀 {defender} talked too much in the wrong saloon. The piano stopped. Bad sign.",
      "💀 {defender} looked for a shortcut through Apache territory. Took it anyway.",
      "💀 {defender}'s wanted poster got an update. 'Deceased.'",
      "💀 {defender} underestimated the bounty hunter. Everyone does, once.",
      "💀 {defender} pulled iron slower than their shadow.",
      "💀 {defender} got bushwhacked at the waterhole. Never let your guard down in the desert.",
    ],
    combatLines: [
      "{attacker} fans the hammer and puts three into {defender}! {damage} HP!",
      "{attacker} draws from the hip and catches {defender} clean! {damage} damage!",
      "{attacker} wings {defender} off a ricochet! {damage} HP — lucky shot!",
      "{attacker} lassos {defender} and drags them through the dust! {damage} damage!",
      "{attacker} catches {defender} with a rifle shot from the ridge! {damage} HP!",
      "{attacker} pistol-whips {defender} with the butt of their Colt! {damage} damage!",
      "{attacker} throws a horseshoe at {defender}! {damage} HP! Unorthodox but effective.",
      "{attacker} rolls under a wagon and fires up at {defender}! {damage} damage!",
      "{attacker} drops {defender} with a boot knife to the thigh! {damage} HP! No fair!",
      "{attacker} fires through the saloon window at {defender}! {damage} damage! Glass everywhere!",
    ],
    flavorLines: [
      "🌵 {player} tips their hat and scans the horizon.",
      "🌅 {player} watches the sun hit the mesa. Beautiful, deadly country.",
      "🐎 {player} checks on their horse. Still there. Good.",
      "🎸 {player} hears a distant guitar. Getting closer.",
      "🪶 {player} reads the dust for tracks. Someone came through here recently.",
      "🔫 {player} spins the cylinder and checks their loads.",
      "🍺 {player} nurses a warm whiskey at the bar. Eyes on the door.",
      "🌪️ {player} sees a dust devil spin up across the flats.",
      "🃏 {player} shuffles a deck of cards. Old habit.",
      "👢 {player} digs a heel spur into the floorboards. Antsy.",
    ],
    eliteLines: [
      "🤠 HIGH NOON: The final four gunslingers face off on Main Street!",
      "🏆 The last chance saloon. One rides out of here a legend.",
    ],
    victoryLine: "🤠 {winner} holsters their iron. The town is safe. For now.",
  },

  space_age: {
    key: 'space_age',
    name: 'Space Age',
    description: 'Laser cannons, zero-G combat, and galactic conquest.',
    exclusive: false,
    lobbyIcon: '🚀',
    lobbyColor: '#1A1AFF',
    lobbyOpening: 'All crew to battle stations. One pilot exits this sector alive.',
    lobbyPlayersLabel: '🚀 Pilots',
    eliminationLines: [
      "💀 {defender} got sucked out of the airlock. Occupational hazard.",
      "💀 {defender} misread a wormhole as a shortcut. It was not a shortcut.",
      "💀 {defender} got clipped by a debris field traveling at 7 km/s.",
      "💀 {defender} trusted their shields at 1%. Shields were not enough.",
      "💀 {defender} ran out of fuel mid-dogfight. Very bad timing.",
      "💀 {defender} got caught in a tractor beam and never pulled out.",
      "💀 {defender} tried to fix the laser cannon while it was charging.",
      "💀 {defender} made first contact. It did not go well.",
      "💀 {defender} piloted into a nebula to hide. The nebula was inhabited.",
      "💀 {defender} forgot to wear their helmet. Space doesn't negotiate.",
      "💀 {defender} got their fighter sliced in half by a capital ship turret.",
      "💀 {defender} drifted into a black hole's event horizon. No U-turn.",
      "💀 {defender} ran a software update mid-combat. Auto-restart. Fatal.",
      "💀 {defender} was fragged by their own torpedo's splash radius.",
      "💀 {defender} tried to trade shots with a dreadnought. In a shuttle.",
    ],
    combatLines: [
      "{attacker} locks phase cannons on {defender} and fires! {damage} HP vaporized!",
      "{attacker} launches a missile spread at {defender}! {damage} damage — shields buckling!",
      "{attacker} rams {defender} in a zero-G broadside! {damage} HP!",
      "{attacker} fires a rail gun slug through {defender}'s hull! {damage} damage!",
      "{attacker} deploys a fighter drone swarm at {defender}! {damage} HP of coordinated chaos!",
      "{attacker} catches {defender} with a plasma burst! {damage} damage — systems offline!",
      "{attacker} activates stealth and stabs {defender} from behind! {damage} HP!",
      "{attacker} fires a gravity bomb at {defender}! {damage} damage! Physics wins again.",
      "{attacker} clips {defender}'s engine pod! {damage} HP and they're spinning!",
      "{attacker} hits {defender} with a focused EMP burst! {damage} damage — everything glitches!",
    ],
    flavorLines: [
      "🌌 {player} stares into the void. The void seems interested.",
      "🛸 {player} spots an unidentified blip on the long-range scanner.",
      "⭐ {player} navigates by starlight. Old school.",
      "🔭 {player} pulls up a star chart. Something's not right.",
      "🛰️ {player} reroutes power from life support to weapons. Bold choice.",
      "👽 {player} receives a transmission in a language they don't recognize. Unsettling.",
      "🚀 {player} burns thrusters to gain altitude. Above the debris field now.",
      "💫 {player} watches a distant supernova light up the sector.",
      "🎮 {player} calibrates targeting systems. Lock and load.",
      "🌙 {player} drifts past a dead moon. Quiet out here. Too quiet.",
    ],
    eliteLines: [
      "🚀 FINAL FOUR: The last fighters converge on the space station. One leaves the sector.",
      "⭐ The galaxy watches. Make history.",
    ],
    victoryLine: "🌌 {winner} achieves total orbital supremacy. Galactic champion!",
  },
};

module.exports = { BATTLE_ERAS };
