/**
 * Battle era configurations.
 * Each era defines themed text lines used during battle simulation.
 * The "mafia" era is the default and always available.
 * Exclusive eras require superadmin assignment to a guild.
 */

const BATTLE_ERAS = {
  mafia: {
    key: 'mafia',
    name: 'Mafia',
    description: 'Classic Solpranos mafia warfare — concrete shoes, cannoli, and family honor.',
    exclusive: false,
    eliminationLines: [
      "☠️ {defender} has been iced. Room temperature.",
      "☠️ {defender} sleeps with the fishes now.",
      "☠️ {defender} got clipped. It's nothing personal, just business.",
      "☠️ {defender} won't be coming back from this one.",
      "☠️ {defender} got whacked. Say goodnight.",
      "☠️ {defender} slipped on a banana peel into a cement mixer. Classic.",
      "☠️ {defender} confused the espresso machine with a tommy gun. Fatal mistake.",
      "☠️ {defender} tried to outrun a horse. The horse won.",
      "☠️ {defender} ate the cannoli that was DEFINITELY poisoned.",
      "☠️ {defender} took a nap in the wrong trunk. Permanent nap.",
      "☠️ {defender} challenged the boss to poker. Lost everything. Including their life.",
      "☠️ {defender} got locked in the walk-in freezer. Very chilly farewell.",
      "☠️ {defender} mistook dynamite for a cigar. Explosive exit.",
      "☠️ {defender} tried to skip out on a tab at Luigi's. Luigi doesn't forget.",
      "☠️ {defender} insulted someone's mother. The streets are ruthless.",
      "☠️ {defender} walked into the wrong social club. Very wrong.",
      "☠️ {defender} bet against the family. Bad investment.",
      "☠️ {defender} forgot to pay respects. The family remembered.",
      "☠️ {defender} accidentally sat in the boss's chair. Last mistake ever.",
      "☠️ {defender} tried to rob the Solpranos piggy bank. Piggy fought back.",
      "☠️ {defender} talked to the feds. The family talked back.",
      "☠️ {defender} laughed at the wrong joke. The punchline was lethal.",
      "☠️ {defender} thought they could swim faster than the concrete. They couldn't.",
      "☠️ {defender} ordered pineapple on pizza at the family dinner. Unforgivable.",
      "☠️ {defender} tried to count cards at Tony's poker night. Tony counted them out.",
      "☠️ {defender} showed up late to a hit. Irony got them first.",
      "☠️ {defender} opened an umbrella indoors. Superstition killed them.",
      "☠️ {defender} spilled wine on the tablecloth. The family spilled their blood.",
      "☠️ {defender} forgot the boss's birthday. The boss didn't forget them.",
      "☠️ {defender} tried to parallel park the getaway car. Still parked there. Forever.",
    ],
    combatLines: [
      "{attacker} sends {defender} to sleep with the fishes for {damage} HP!",
      "{attacker} delivers an offer {defender} can't refuse - {damage} damage!",
      "{attacker} whacks {defender} with a tire iron for {damage} HP!",
      "{attacker} gives {defender} a concrete shoe fitting - {damage} damage!",
      "{attacker} breaks {defender}'s kneecaps for {damage} HP!",
      "{attacker} puts a hit on {defender} - {damage} damage taken!",
      "{attacker} makes {defender} kiss the ring... with their face! {damage} HP!",
      "{attacker} pistol-whips {defender} for {damage} damage!",
      "{attacker} sends {defender} a message - {damage} HP worth!",
      "{attacker} shows {defender} who's boss - {damage} damage!",
      "{attacker} throws {defender} through a window! {damage} HP shattered!",
      "{attacker} introduces {defender} to their baseball bat! {damage} damage!",
    ],
    flavorLines: [
      "🚬 {player} lights up a cigar and contemplates life.",
      "📞 {player} gets a call from the boss. 'Keep it clean.'",
      "🎰 {player} checks the numbers from last night's game.",
      "🚗 {player} hears sirens in the distance. Feds getting close.",
      "🎵 {player} hums 'That's Amore' while reloading.",
      "💼 {player} checks the briefcase. Everything's there.",
      "🍷 {player} swirls a glass of expensive wine.",
      "🕊️ {player} feeds the pigeons. Even killers have hobbies.",
      "🎭 {player} practices their alibi in the mirror.",
      "🌃 {player} admires the skyline. Beautiful city. Violent, but beautiful.",
      "🔫 {player} cleans their gun. Maintenance is important.",
      "📰 {player} reads the obituaries. Checking for friends.",
      "🎪 {player} juggles grenades. Just kidding. Or are they?",
      "🚪 {player} checks the exits. Always have an escape plan.",
      "👔 {player} adjusts their tie. Looking sharp for the funeral. Theirs? Who knows.",
      "🎬 {player} quotes The Godfather. Classic move.",
      "🍝 {player} debates opening a legitimate restaurant. Nah.",
      "💰 {player} counts money nervously. Is it all there?",
      "🚕 {player} hails a cab. Wait, that's not a cab driver...",
      "🎲 {player} rolls dice on the ground. Snake eyes. Bad omen.",
      "📱 {player} checks their burner phone. 47 missed calls from mom.",
      "🏪 {player} window-shops at the corner store. Maybe they'll rob it later.",
      "⛪ {player} says a quick prayer. Insurance policy.",
      "🎺 {player} hears jazz in the distance. Classy.",
      "🌹 {player} smells a rose. Then sneezes violently.",
      "🚬 {player} offers someone a cigarette. Declined. Rude.",
      "🎩 {player} tips their fedora at a passing stranger.",
      "🍕 {player} debates pineapple on pizza. Decides against it. Smart.",
      "🔮 {player} visits a fortune teller. 'I see violence.' No kidding.",
      "🎸 {player} air-guitars to Frank Sinatra. Embarrassing.",
    ],
  },

  vault_runners: {
    key: 'vault_runners',
    name: 'Vault Runners',
    description: 'Incompetent criminals pulling a heist. Ocean\'s Eleven meets Arrested Development.',
    exclusive: true,
    eliminationLines: [
      "💀 {defender} triggered the alarm by sneezing into the motion sensor. {attacker} shoved them into the laser grid on the way out.",
      "💀 {attacker} \"accidentally\" closed the vault door on {defender}. The time lock is set for 72 hours. Good luck in there.",
      "💀 {defender} got tangled in their own grappling hook and {attacker} just... watched. Popcorn and everything.",
      "💀 {attacker} swapped {defender}'s smoke bomb with a flashbang. {defender} is now blind AND arrested.",
      "💀 {defender} tried to crawl through the air vent. Got stuck at the first turn. {attacker} sealed it shut.",
      "💀 {attacker} told {defender} the getaway car was in Lot B. There is no Lot B. {defender} is still looking.",
      "💀 {defender}'s disguise was a name tag that said 'NOT A CRIMINAL.' Security disagreed. {attacker} waved goodbye.",
      "💀 {attacker} used {defender} as a human shield when the security guard dog showed up. The dog chose violence.",
      "💀 {defender} accidentally called 911 instead of the crew's burner. Gave their full name and location. {attacker} is already in the car.",
      "💀 {attacker} convinced {defender} the vault combination was their birthday. It wasn't. The alarm was loud.",
      "💀 {defender} left fingerprints on EVERYTHING including the 'Please Do Not Touch' sign. {attacker} tipped off forensics for fun.",
      "💀 {defender}'s flashlight batteries died at the worst possible moment. {attacker}'s didn't. Nature selected.",
      "💀 {attacker} told {defender} to \"hold this\" and handed them a dye pack. Three... two... one... purple.",
      "💀 {defender} wore squeaky shoes to a stealth heist. {attacker} heard them from three floors away. So did everyone else.",
      "💀 {attacker} reprogrammed the signal jammer to only jam {defender}'s radio. {defender} has been talking to nobody for twenty minutes.",
      "💀 {defender} grabbed what they thought was the diamond. It was a paperweight from the gift shop. {attacker} has the real one.",
      "💀 {defender} tried to hack the security system by typing 'password123'. It worked. Then {attacker} changed it.",
    ],
    arrestLines: [
      "🚔 {defender} got tackled by a security guard who was honestly just having a really bad day. {attacker} filmed it.",
      "🚔 {attacker} anonymously reported {defender}'s location to the cops. From ten feet away. While waving.",
      "🚔 {defender} tried to bribe the guard with Monopoly money. The guard was not amused. {attacker} provided the handcuffs.",
      "🚔 {defender} ran straight into a glass door trying to escape. Left a face print. {attacker} signed it as modern art.",
      "🚔 {defender} hid in a storage closet. It was the security office. {attacker} locked it from outside.",
      "🚔 The K-9 unit found {defender} because they had bacon in their pocket. WHY did they have bacon? {attacker} knows why.",
      "🚔 {defender} tried to blend in with the mannequins. Blinked. {attacker} yelled 'THAT ONE MOVED!' Very helpful.",
      "🚔 {defender} was caught because their getaway vehicle was a shopping cart. {attacker} popped the wheels earlier.",
      "🚔 {defender} surrendered after the security guard's walkie-talkie static scared them. {attacker} made the static noise.",
      "🚔 {defender} got arrested for trespassing, breaking and entering, AND an overdue library book. {attacker} planted the book.",
    ],
    flavorLines: [
      "🔦 {player} realizes their night-vision goggles are actually swim goggles painted black.",
      "📻 {player}'s earpiece starts picking up a local jazz station. They vibe for a second. Focus.",
      "🧤 {player} puts on their heist gloves. They're oven mitts. Close enough.",
      "🚗 {player} checks on the getaway car. It has a boot on it. That's new.",
      "🗺️ {player} unfolds the blueprint. It's upside down. Has been this whole time.",
      "💡 {player} accidentally triggers a hallway light. Freezes like a deer. Nobody noticed. Maybe.",
      "🎭 {player} adjusts their ski mask. It's on backwards. They can smell their own breath.",
      "📱 {player}'s phone goes off. The ringtone is the Mission Impossible theme. Irony is dead.",
      "🔑 {player} picks a lock in 3 seconds. Wrong door. That's a broom closet.",
      "🐕 {player} hears the security dog barking. Throws a steak. It's frozen solid. The dog is confused.",
      "💎 {player} spots the target vault. It's smaller than expected. Also it might be a safe deposit box.",
      "🧱 {player} tries to cut through a wall. Hits a water pipe. The heist is now also a pool party.",
      "🚨 {player} walks through a metal detector they didn't see. Everything beeps. Even their belt.",
      "📹 {player} waves at a security camera. Realizes. Puts hand down slowly. Damage done.",
      "🧊 {player} slips on a freshly mopped floor. The janitor watches. Judges silently.",
      "🎒 {player} opens their heist bag. It's full of sandwiches. Wrong bag. But honestly, needed those.",
      "🔧 {player} assembles the drill. Three parts are left over. That can't be good.",
      "🚪 {player} tries to open a push door by pulling. For thirty seconds. The camera got all of it.",
      "💨 {player} uses a smoke bomb for cover. In a room with smoke detectors. Sprinklers activate.",
      "🎵 {player} starts humming the heist music. The crew tells them to shut up. They hum quieter.",
      "🧲 {player} brought a magnet to disable the electronic lock. It disabled their own phone instead.",
      "📦 {player} hides behind a cardboard box. Metal Gear style. A guard kicks it. {player} says 'ow.'",
    ],
    combatLines: [
      "{attacker} throws a bag of stolen jewels at {defender}'s face! {damage} damage and a lot of scattered diamonds!",
      "{attacker} swings a gold bar at {defender}! {damage} HP of premium damage!",
      "{attacker} shoves {defender} into the laser grid! {damage} HP and a very geometric sunburn!",
      "{attacker} drops a ceiling tile on {defender} from the air vent! {damage} damage! Stealth: failed.",
      "{attacker} hits {defender} with a fire extinguisher! {damage} HP! Safety first, violence second.",
      "{attacker} throws a flash drive full of evidence at {defender}! {damage} damage! That's... not how you destroy evidence.",
      "{attacker} trips {defender} with a grappling hook! {damage} HP! Multi-purpose tool.",
      "{attacker} slams {defender} with a vault door! {damage} damage! That's gonna need some ice. And a chiropractor.",
      "{attacker} blinds {defender} with a laser pointer and kicks them down the stairs! {damage} HP!",
      "{attacker} releases the security dog on {defender}! {damage} damage! Bad dog. Good chaos.",
      "{attacker} hits {defender} with a duffle bag full of cash! {damage} HP! Most expensive punch ever.",
      "{attacker} shoves {defender} into the dye pack storage! {damage} damage and they're now bright purple!",
    ],
  },
};

module.exports = { BATTLE_ERAS };
